### ISSUE TITLE
Crash when reading a specific file

### ISSUE THREAD

**Issue by cspiegel** [Konstanty/libmodplug#27]
[breaking the walls.mdl](http://modland.com/pub/modules/Digitrakker/Lard/breaking%20the%20walls.mdl) causes libmodplug to crash when it's loaded:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7a75095 in MDLReadBits (bitbuf=@0x7ffffffd6000: 0, bitnum=@0x7ffffffd6004: 24, 
    ibuf=@0x7ffffffd6008: 0x7ffffffff001 <error: Cannot access memory at address 0x7ffffffff001>, n=n@entry=1 '\001') at load_mdl.cpp:497
497         bitbuf |= (((DWORD)(*ibuf++)) << bitnum);
(gdb) bt
#0  0x00007ffff7a75095 in MDLReadBits (bitbuf=@0x7ffffffd6000: 0, bitnum=@0x7ffffffd6004: 24, 
    ibuf=@0x7ffffffd6008: 0x7ffffffff001 <error: Cannot access memory at address 0x7ffffffff001>, n=n@entry=1 '\001') at load_mdl.cpp:497
#1  0x00007ffff7a5e02e in CSoundFile::ReadSample (this=this@entry=0x612c20, pIns=pIns@entry=0x61c320, nFlags=<optimized out>, 
    lpMemFile=lpMemFile@entry=0x7ffffffdbb07 "B\b\221\344\036B\006\317\062<\255g\351=\352\352P\v]\342~\005%X\265\004\374z\017Vd,^:\006{7R\004q\213\f\254\n\217SDi\036\214\032\363\033S\023\312\065>n*\336\352s\367\342\332\024\203@\372\263\071V\003'yRJ\260JE\211\231\353\310\363V5̐\232\240\245\025\300\213H\253t\246$\357\252\301\245\177\363\237ޜB\002W\330&\bY%\312\070\067\223\306J\304*\325\331\060SJ\260v\220\340a\311\360\360\020\061T\230MY\307Ȕ\231%\274\022\224\202\205\235\216\300\217\302k\262Y\221\340<\214J*\240\246\261B\207\003B@\204\313\016\021\r\202N;ة\235L*+\001%2\302I\361\270\357e"..., 
    dwMemLength=dwMemLength@entry=5404) at sndfile.cpp:1420
#2  0x00007ffff7a74a38 in CSoundFile::ReadMDL (this=this@entry=0x612c20, lpStream=<optimized out>, dwMemLength=142719) at load_mdl.cpp:401
#3  0x00007ffff7a5c869 in CSoundFile::Create (this=this@entry=0x612c20, lpStream=lpStream@entry=0x7ffffffda030 "DMDL", 
    dwMemLength=dwMemLength@entry=142719) at sndfile.cpp:152
#4  0x00007ffff7a8ff77 in ModPlug_Load (data=0x7ffffffda030, size=142719) at modplug.cpp:88
#5  0x00000000004007a4 in main () at t.c:15
```

This occurs in master as well as 0.8.8.5.

**Comment by sezero** [comment]
This seems to be because libmodplug isn't handling version 0 files.
(It also doesn't byte swap word and dword values, so it should fail on big endian too.)
I have a patch, based on data from libopenmpt, will post shortly.

**Comment by sezero** [comment]
This should fix things:
https://github.com/sezero/libmodplug/commit/429a523b24dc70c0b8e476e52ec08e08aca70a09

**Comment by sezero** [comment]
These changes seem to have been merged: this issue should be closed as fixed.

**Comment by Konstanty** [comment]
Cool
